config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  get "/blogposts/new" => "articles#new", as: :new_blogpost
  post "blogposts" => "articles#create", as: :blogposts

  get "/blogposts/:id" => "articles#show", as: :blogpost
  get "blogposts/:id/edit" => "articles#edit", as: :edit_blogpost
  patch "blogposts/:id" => "articles#update", as: :blogpost_updated

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @blogposts = Blogpost.all
  end

  def new
    @blogpost = Blogpost.new
  end

  def show
    @blogpost = Blogpost.find params[:id]
  end

  def create
    @blogpost = Blogpost.new(params.require(:blogpost).permit(:title, :body, :published_on))
    if @blogpost.save
      redirect_to root_path
    else
      # allow user to fill out form again?
      render :new
    end
  end

  def edit
    @blogpost = Blogpost.find params[:id]
  end

  def update
    @blogpost = Blogpost.find params[:id]
    if @blogpost.update params.require(:blogpost).permit(:title, :body, :published_on)
      redirect_to root_path
    else
      render :edit
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container">
<%= form_for @blogpost do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_field :body, class: "form-control"  %>
  </div>

  <!-- <div class="form-group">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url, class: "form-control"  %>
  </div> -->

  <div class="form-group">
    <%= f.label :published_on %>
    <%= f.date_select :published_on, class: "form-group"  %>
  </div>

  <div>
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

</div>

app/views/articles/edit.html.erb
<h1>Editing a post. </h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<div class="container">
<h1> Index: </h1>



  <%= link_to "New Post", '/blogposts/new', class: "btn btn-danger pull-right" %>


    <% @blogposts.each do |blogpost| %>
    <br>
    <div class="post">
      <!-- <%= blogpost.title %> -->
        <h2>
        <%= link_to blogpost.title, blogpost %>
        </h2>
        <!-- <%= image_tag blogpost.photo_url, class: "thumb" %> -->
        <%= blogpost.published_on.strftime('Published on: %d-%m-%Y') %>
        <%= link_to "Edit", edit_blogpost_path(blogpost) %>
    <% end %>
    </div>


</div>

app/views/articles/new.html.erb
New Blogpost!

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<%= link_to "Home", root_path %>

<h1><%= @blogpost.title %></h1>

<h2>body: <%= @blogpost.body %></h2>



<!-- <%= image_tag @blogpost.photo_url %> -->

<h4> <%= @blogpost.published_on %> </h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogposts</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>